"""add thread_id to llm_call_logs

Revision ID: 40046ce16ad0
Revises: ec3e8447dd30
Create Date: 2026-10-09 15:57:22.308806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40046ce16ad0'
down_revision: Union[str, Sequence[str], None] = 'ec3e8447dd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_llm_call_logs_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_thread_id'))
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
