"""add is_active to users

Revision ID: 830983e1bfd8
Revises: deb230aa5caa
Create Date: 2026-10-09 19:30:38.625561

停用标记。用户不做硬删除（见 src/models/database.py 中该列的说明：
外键未声明 ondelete，硬删在 PostgreSQL 上会违反外键，且会让历史评估指向不存在的人）。

server_default='1'：已有行必须立刻可取到值，否则 NOT NULL 加列会失败。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830983e1bfd8'
down_revision: Union[str, Sequence[str], None] = 'deb230aa5caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
